import { ckeditorFileRepositoryUploadAdapterPlugin } from '@/utils/ckeditorUploadAdapter.js';

/**
 * Cấu hình Classic Editor “đầy đủ” trong phạm vi CKEditor 5 (CDN cloud).
 * Không thể giống hệt CKEditor 4 Full (Flash, form field, Print… không có trong CK5).
 */
export function getCkEditorClassicFullConfig({ cloudData, licenseKey }) {
  if (!cloudData?.CKEditor) return null;

  const ck = cloudData.CKEditor;
  const premium = cloudData.CKEditorPremiumFeatures || {};

  const {
    Essentials,
    Paragraph,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Subscript,
    Superscript,
    Code,
    RemoveFormat,
    BlockQuote,
    Alignment,
    Font,
    Link,
    List,
    ListProperties,
    TodoList,
    Indent,
    IndentBlock,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    TableCaption,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageTextAlternative,
    ImageResize,
    AutoImage,
    ImageUpload,
    ImageInsert,
    ImageInsertViaUrl,
    MediaEmbed,
    SpecialCharacters,
    SpecialCharactersEssentials,
    Highlight,
    Typing,
    Heading,
    SourceEditing,
    Autoformat,
    FindAndReplace,
    WordCount,
    HorizontalLine,
    PageBreak,
    CodeBlock,
    PasteFromOffice,
    ShowBlocks,
    Emoji,
    EmojiPicker,
    EmojiRepository,
    Bookmark,
    Autosave,
  } = ck;

  const FormatPainter = premium.FormatPainter;

  const plugins = [
    Essentials,
    Paragraph,
    Typing,
    PasteFromOffice,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Subscript,
    Superscript,
    Code,
    RemoveFormat,
    BlockQuote,
    Alignment,
    Font,
    Link,
    List,
    ListProperties,
    TodoList,
    Indent,
    IndentBlock,
    Heading,
    Autoformat,
    HorizontalLine,
    PageBreak,
    Table,
    TableToolbar,
    TableCaption,
    TableProperties,
    TableCellProperties,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageTextAlternative,
    ImageResize,
    AutoImage,
    ImageUpload,
    ImageInsert,
    ImageInsertViaUrl,
    MediaEmbed,
    SpecialCharacters,
    SpecialCharactersEssentials,
    Highlight,
    SourceEditing,
    FindAndReplace,
    WordCount,
    CodeBlock,
    ShowBlocks,
    Emoji,
    EmojiPicker,
    EmojiRepository,
    Bookmark,
    Autosave,
    ckeditorFileRepositoryUploadAdapterPlugin,
  ];

  if (FormatPainter) {
    plugins.push(FormatPainter);
  }

  return {
    licenseKey,
    plugins,
    heading: {
      options: [
        { model: 'paragraph', title: 'Đoạn', class: 'ck-heading_paragraph' },
        { model: 'heading1', view: 'h1', title: 'Tiêu đề 1', class: 'ck-heading_heading1' },
        { model: 'heading2', view: 'h2', title: 'Tiêu đề 2', class: 'ck-heading_heading2' },
        { model: 'heading3', view: 'h3', title: 'Tiêu đề 3', class: 'ck-heading_heading3' },
        { model: 'heading4', view: 'h4', title: 'Tiêu đề 4', class: 'ck-heading_heading4' },
      ],
    },
    image: {
      toolbar: [
        'imageTextAlternative',
        '|',
        'imageStyle:inline',
        'imageStyle:block',
        'imageStyle:side',
        '|',
        'toggleImageCaption',
        '|',
        'resizeImage',
      ],
    },
    table: {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        'toggleTableCaption',
        '|',
        'tableProperties',
        'tableCellProperties',
      ],
    },
    autosave: {
      save() {
        return Promise.resolve();
      },
    },
    typing: { enable: true },
    toolbar: [
      [
        'sourceEditing',
        '|',
        'undo',
        'redo',
        '|',
        'findAndReplace',
        '|',
        'showBlocks',
        '|',
        'specialCharacters',
        'emoji',
      ],
      [
        'heading',
        '|',
        'fontFamily',
        'fontSize',
        'fontColor',
        'fontBackgroundColor',
        '|',
        'bold',
        'italic',
        'underline',
        'strikethrough',
        'subscript',
        'superscript',
        'code',
        'removeFormat',
        '|',
        'highlight',
        ...(FormatPainter ? ['formatPainter'] : []),
      ],
      [
        'alignment',
        '|',
        'outdent',
        'indent',
        '|',
        'bulletedList',
        'numberedList',
        'todoList',
        '|',
        'link',
        'bookmark',
        'blockQuote',
      ],
      [
        'insertTable',
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        '|',
        'horizontalLine',
        'pageBreak',
        '|',
        'insertImage',
        'mediaEmbed',
      ],
      ['codeBlock', '|', 'mathType', '|', 'wordCount', 'autoSave'],
    ],
  };
}
