import { ckeditorFileRepositoryUploadAdapterPlugin } from '@/utils/ckeditorUploadAdapter.js';

/**
 * CKEditor 5 cho ô "Nội dung" câu hỏi: tiếng Việt, chèn ảnh (upload + URL qua insertImage).
 * Không thể trùng hộp thoại CKEditor 4 trong ảnh mẫu — đó là CK4.
 */
export function buildProblemRichTextEditorConfig(cloudData, licenseKey) {
  if (!cloudData?.CKEditor) return null;

  const ck = cloudData.CKEditor;
  const premium = cloudData.CKEditorPremiumFeatures || {};
  const { FormatPainter } = premium;

  const {
    Essentials,
    Paragraph,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    BlockQuote,
    Alignment,
    Font,
    FontSize,
    FontColor,
    FontBackgroundColor,
    Link,
    List,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageTextAlternative,
    ImageResize,
    AutoImage,
    ImageUpload,
    ImageInsert,
    ImageInsertViaUrl,
    MediaEmbed,
    SpecialCharacters,
    SpecialCharactersEssentials,
    Highlight,
    Heading,
    SourceEditing,
    Autoformat,
    FindAndReplace,
    WordCount,
    Autosave,
  } = ck;

  const plugins = [
    Essentials,
    Paragraph,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    BlockQuote,
    Alignment,
    Font,
    FontSize,
    FontColor,
    FontBackgroundColor,
    Link,
    List,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageTextAlternative,
    ImageResize,
    AutoImage,
    ImageUpload,
    ImageInsert,
    ImageInsertViaUrl,
    MediaEmbed,
    SpecialCharacters,
    SpecialCharactersEssentials,
    Highlight,
    Heading,
    SourceEditing,
    Autoformat,
    FindAndReplace,
    WordCount,
    Autosave,
  ];
  if (FormatPainter) plugins.push(FormatPainter);

  return {
    licenseKey,
    language: 'vi',
    plugins,
    extraPlugins: [ckeditorFileRepositoryUploadAdapterPlugin],
    heading: {
      options: [
        { model: 'paragraph', title: 'Đoạn', class: 'ck-heading_paragraph' },
        { model: 'heading1', view: 'h1', title: 'Tiêu đề 1', class: 'ck-heading_heading1' },
        { model: 'heading2', view: 'h2', title: 'Tiêu đề 2', class: 'ck-heading_heading2' },
        { model: 'heading3', view: 'h3', title: 'Tiêu đề 3', class: 'ck-heading_heading3' },
      ],
    },
    image: {
      toolbar: [
        'imageTextAlternative',
        '|',
        'imageStyle:inline',
        'imageStyle:block',
        'imageStyle:side',
        '|',
        'toggleImageCaption',
        '|',
        'resizeImage',
      ],
    },
    autosave: {
      save() {
        return Promise.resolve();
      },
    },
    typing: { enable: true },
    toolbar: [
      'sourceEditing',
      '|',
      'undo',
      'redo',
      '|',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      '|',
      'heading',
      'fontSize',
      'fontColor',
      'fontBackgroundColor',
      '|',
      'alignment',
      'outdent',
      'indent',
      '|',
      'bulletedList',
      'numberedList',
      '|',
      'link',
      'blockQuote',
      'specialCharacters',
      'highlight',
      '|',
      'insertTable',
      'tableColumn',
      'tableRow',
      'mergeTableCells',
      'tableProperties',
      'tableCellProperties',
      '|',
      'insertImage',
      'mediaEmbed',
      '|',
      'mathType',
      '|',
      'findAndReplace',
      'wordCount',
      'autoSave',
      ...(FormatPainter ? ['|', 'formatPainter'] : []),
    ],
  };
}
